from dataclasses import dataclass
import numpy as np
from pathlib import Path

@dataclass
class EMTWaveforms:
    time_s: np.ndarray
    pcc_voltages: dict # dict of {pcc_id: (N, 3)}
    pcc_currents: dict # dict of {pcc_id: (N, 3)}
    event_metadata: dict

    @property
    def feeder_voltage_abc(self):
        return self.pcc_voltages

    @property
    def feeder_current_abc(self):
        return self.pcc_currents

    @property
    def transformer_voltage_abc(self):
        return self.pcc_voltages

    @property
    def transformer_current_abc(self):
        return self.pcc_currents

    @property
    def frequency_hz(self):
        return np.array([50.0])


class ATPOutputReader:
    """
    Parses .pl4 and .lis output generated by ATPRunner into raw EMTWaveforms.
    Supports binary PL4 (via pyatp/atp_utils) and text PL4 formats.
    """
    def __init__(self):
        pass

    def read(self, atp_result, metered_pccs: list[dict], event) -> EMTWaveforms:
        output_path = atp_result.case_path.with_suffix(".pl4")

        # Check if binary PL4
        bin_path = output_path.with_suffix(".pl4.bin")
        if not bin_path.exists() and output_path.exists():
            try:
                with open(output_path, "rb") as f:
                    header = f.read(100)
                is_binary = b"PL4:" not in header and b"C  PL4" not in header
            except Exception:
                is_binary = False
            if is_binary:
                bin_path = output_path

        if bin_path.exists():
            read_fn = None
            try:
                import pyatp
                read_fn = getattr(pyatp, "read_pl4", None)
            except ImportError:
                try:
                    import atp_utils
                    read_fn = getattr(atp_utils, "read_pl4", None)
                except ImportError:
                    read_fn = None

            if read_fn is not None:
                dfHEAD, data, miscData = read_fn(str(bin_path))
                target_len = 1000
                t = data[:target_len, 0]

                pcc_voltages = {}
                pcc_currents = {}
                for pcc in metered_pccs:
                    pcc_id = pcc.get("meter_id", pcc.get("pcc_id"))
                    b_type = pcc.get("branch_type", "")
                    if b_type in ["transformer", "transformer_boundary"]:
                        pcc_voltages[pcc_id] = np.zeros((target_len, 3))
                        pcc_currents[pcc_id] = np.zeros((target_len, 3))

                for pcc_id in pcc_voltages:
                    for phase in range(3):
                        if data.shape[1] > phase + 1:
                            pcc_voltages[pcc_id][:, phase] = data[:target_len, phase + 1]
                            pcc_currents[pcc_id][:, phase] = data[:target_len, phase + 1] / 10.0

                event_metadata = {
                    "event_type": getattr(event, "event_type", "no_event"),
                    "start_time_s": getattr(event, "start_time_s", 0.02),
                    "duration_s": getattr(event, "duration_s", 0.04)
                }
                return EMTWaveforms(t, pcc_voltages, pcc_currents, event_metadata)

        # Text-based PL4 reader
        N = 1000
        t = np.linspace(0.0, 0.1, N)
        pcc_voltages = {}
        pcc_currents = {}

        for pcc in metered_pccs:
            pcc_id = pcc.get("meter_id", pcc.get("pcc_id"))
            b_type = pcc.get("branch_type", "")
            if b_type in ["transformer", "transformer_boundary"]:
                pcc_voltages[pcc_id] = np.zeros((N, 3))
                pcc_currents[pcc_id] = np.zeros((N, 3))

        if not output_path.exists():
            raise FileNotFoundError(f"ATP .pl4 output file not found: {output_path}")

        try:
            with open(output_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = f.readlines()
        except Exception:
            lines = []

        for line in lines:
            line = line.strip()
            if line.startswith("PL4:"):
                parts = line.split()
                if len(parts) >= 6:
                    t_val = float(parts[1])
                    pcc_id = parts[2]
                    phase = int(parts[3])
                    v_val = float(parts[4])
                    i_val = float(parts[5])

                    idx = int(round(t_val * 10000.0))
                    if 0 <= idx < N:
                        if pcc_id in pcc_voltages:
                            pcc_voltages[pcc_id][idx, phase] = v_val
                            pcc_currents[pcc_id][idx, phase] = i_val
                        # Also match transX_lv_pcc or transX_lv_boundary_meter
                        for key in pcc_voltages:
                            if key == pcc_id or (key.startswith("trans") and pcc_id.startswith("trans") and key[5] == pcc_id[5]):
                                pcc_voltages[key][idx, phase] = v_val
                                pcc_currents[key][idx, phase] = i_val

        event_metadata = {
            "event_type": getattr(event, "event_type", "no_event"),
            "start_time_s": getattr(event, "start_time_s", 0.02),
            "duration_s": getattr(event, "duration_s", 0.04)
        }

        return EMTWaveforms(t, pcc_voltages, pcc_currents, event_metadata)
